### ISSUE TITLE
Getting the models

### ISSUE THREAD

**Issue by markusmobius** [AIFanatic/google-offline-speech-recognition#3]
I downloaded google quick search box version 11.7.11.21 (x86_64).

I found the libgoogle_speech_jni.so library library.

However, there is no data/data folder (for the models) inside the unzipped apk file. Am I looking in the wrong place?

**Comment by AIFanatic** [comment]
Wrong place, the models do not come with the apk they are downloaded separately.
When you enable offline speech the app will download the models into its own folder, usually under /data/data/<com.app>
You need a rooted device to access the files.
