### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 0wwafa** [AIFanatic/google-offline-speech-recognition#6]
if you do `find / 2>/dev/null -name "*.tflite" >tflite.txt` on any android phone you find TONS of models.

The most interesting ar the offline TTS and STT from google... bot in searchbox app and gboard.
There is also an offline transcription mopdel in the latest pixel 8/samsung s24recorder app but it's only for english.

I think it would br great to run the on low end PCs or raspberry pi using tensorflow lite and some python magic...

**Comment by biemster** [comment]
The models from the recorder app should be compatible with libsoda from chrome, but this requires a not too old CPU (not more than about 10 years or so), and x86. I still did not find a soda lib that will work on rpi.

**Comment by 0wwafa** [comment]
> The models from the recorder app should be compatible with libsoda from chrome, but this requires a not too old CPU (not more than about 10 years or so), and x86. I still did not find a soda lib that will work on rpi.

I just wish there was a small and fast utility like llama.ccp to run those tflite models from a PC.

**Comment by biemster** [comment]
Since you are here I guess you know about https://github.com/biemster/gasr, what is blocking you from using that for your use case?

**Comment by 0wwafa** [comment]
> Since you are here I guess you know about https://github.com/biemster/gasr, what is blocking you from using that for your use case?

nothing.. I just was thinking at something more straightforward.
